[package]
name = "sgb-socks5"
version = "0.1.0"
authors = ["esukmean <esukmean@esukmean.com>"]
edition = "2018"

[lib]
name = "tokio_socks5"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features=["full", "rt", "net"] }
byteorder = "1"
dnsclient = "*"
lazy_static = "*"
rand = "*"
